name: Generate STL and Thumbnails using OpenSCAD

on:
  push:
    paths:
      - "*/**/*.txt"
      - "*/**/*.scad"
      - ".github/workflows/**/*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OpenSCAD, WebP tools, and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y openscad webp xvfb

      - name: Generate STL files and multiple PNG thumbnails
        run: |
          xvfb-run -a --server-args="-screen 0 1024x768x24" bash -c '
            find . -name "*.scad" | grep -v "^./lib/" | while read scad; do
                stl_path="${scad%.scad}.stl"
                openscad -o $stl_path $scad
                angles=(
                  "0,0,0,65,0,25,100"
                  "0,0,0,65,0,205,100"
                  "0,0,0,25,25,25,100"
                  "0,0,0,-155,-25,0,100"
                )
                thumbnail_counter=1
                for angle in "${angles[@]}"; do
                    png_path="${scad%.scad}_$thumbnail_counter.png"
                    openscad --camera=$angle --colorscheme="Tomorrow" --render --imgsize=512,512 -o $png_path $scad
                    thumbnail_counter=$((thumbnail_counter + 1))
                done
            done
          '

      - name: Convert PNG thumbnails to WebP
        run: |
          for png in $(find . -name "*.png"); do
              cwebp $png -o ${png%.png}.webp
          done

      - name: Clean up directory (Only keep STL and WebP files and txt descriptions)
        run: |
          find . ! -path "./.git/*" ! -name ".git" -type f ! \( -name "*.stl" -o -name "*.webp" -o -name "*.txt" \)  -exec rm -rf {} \;

      - name: Generate index.html
        run: |
          repo_url="https://github.com/$GITHUB_REPOSITORY/blob/gh-pages"
          echo "<!DOCTYPE html><html><head><link href='https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css' rel='stylesheet'></head><body>" > index.html
          find . -name "*.stl" | while read stl; do
            scad_name="${stl%.stl}.scad"
            txt_name="${stl%.stl}.txt"
            link="$repo_url/$stl"
            title="${stl#./}"  # Removing './' from the title
            echo "<h2 class='text-2xl font-bold'><a href='$link'>$title</a></h2>" >> index.html
            if [ -f $txt_name ]; then
                cat $txt_name | sed 's/$/<br\/>/' >> index.html
            fi
            thumbnail_counter=1
            echo "<div class='inline-block'>" >> index.html  # Create a container for the thumbnails
            while [ $thumbnail_counter -le 4 ]; do
                webp_name="${stl%.stl}_$thumbnail_counter.webp"
                echo "<a href='$link'><img class='w-24 h-24' src='$webp_name' title='$title'></a>" >> index.html
                thumbnail_counter=$((thumbnail_counter + 1))
            done
            echo "</div>" >> index.html
          done
          echo "</body></html>" >> index.html

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "masuidrive@users.noreply.github.com"
          git checkout -b gh-pages
          git add **/*.stl **/*.webp index.html
          git commit -m "Update STL files and thumbnails of https://github.com/$GITHUB_REPOSITORY"
          git push -f origin gh-pages
